### ISSUE TITLE
cannot make uf2

### ISSUE THREAD

**Issue by phillowcompiler** [microsoft/uf2#28]
The following error message was output 

```
Traceback (most recent call last):
  File "uf2/utils/uf2conv.py", line 314, in <module>
    main()
  File "uf2/utils/uf2conv.py", line 290, in main
    outbuf = convert_to_carray(inpbuf)
  File "uf2/utils/uf2conv.py", line 99, in convert_to_carray
    outp += "0x%02x, " % file_content[i]
TypeError: %x format: a number is required, not str
```
I think it's due to the last  changes.
https://github.com/microsoft/uf2/commit/41394bd604e341ebcfdf0a8c4acce9ec8fd73d93

**Comment by mmoskal** [comment]
are you on Python2 or 3?

**Comment by phillowcompiler** [comment]
python -V
Python 2.7.17

is ver.3 better?

**Comment by phillowcompiler** [comment]
Thanks
I changed using python3.6 as updateupdate-alternatives.

Its OK.　;-)
